# runner_types:
#   runner_label:
#     instance_type: m4.large
#     os: linux
#     max_available: 20
#     disk_size: 50

runner_types:
  linux.2xlarge:
    instance_type: c5.2xlarge
    os: linux
    max_available: 200
    disk_size: 100
  linux.8xlarge.nvidia.gpu:
    instance_type: g3.8xlarge
    os: linux
    max_available: 50
    disk_size: 100
  windows.2xlarge:
    instance_type: c5.2xlarge
    os: windows
    max_available: 200
    disk_size: 256
  windows.8xlarge.nvidia.gpu:
    instance_type: g3.8xlarge
    os: windows
    max_available: 50
    disk_size: 256
