version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3
    steps:
      - run:
          name: This should run after everything else
          command: echo "This is CIRCLE_PR_NUMBER '${CIRCLE_PR_NUMBER}'"

workflows:
  version: 2.1
  default:
    jobs:
      - test
