name: Reserve Github Actions Runner

on:
  workflow_dispatch:
    inputs:
      runnerType:
        description: 'The type of runner you would like to reserve'
        default: "linux.2xlarge"

jobs:
  reserve-runner:
    runs-on: ${{ github.event.inputs.runnerType }}
    steps:
      - name: Setup tmate session for ${{ github.event.inputs.runnerType }}
        uses: mxschmitt/action-tmate@18c3652e863e41474701cc45349bfc24a902636e #v3.5
        timeout-minutes: 120 # 2 hours
        with:
          limit-access-to-actor: true
