name: Reserve Github Actions Runner

on:
  workflow_dispatch:
    inputs:
      runnerType:
        description: 'The type of runner you would like to reserve'
        default: "linux.2xlarge"

jobs:
  reserve-runner:
    runs-on: ${{ github.event.inputs.runnerType }}
    steps:
      - name: Setup tmate session for ${{ github.event.inputs.runnerType }}
        uses: seemethere/action-tmate@b4969583bce5fa9a00428f967134d434dbc416f6
        timeout-minutes: 120 # 2 hours
        with:
          limit-access-to-actor: true
          install_dependencies: false
