name: verify
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  # test-linux-cpu:
  #   runs-on: "linux.2xlarge"
  #   steps:
  #     - name: Print runner information
  #       run: cat /etc/os-release
  # test-linux-gpu:
  #   runs-on: "linux.8xlarge.nvidia.gpu"
  #   steps:
  #     - name: Print runner information
  #       run: cat /etc/os-release
  #     - name: Install nvidia-smi
  #       run: |
  #           sudo yum groupinstall -y "Development Tools"
  #           DRIVER_FN="NVIDIA-Linux-x86_64-460.39.run"
  #           wget "https://s3.amazonaws.com/ossci-linux/nvidia_driver/$DRIVER_FN"
  #           sudo /bin/bash "$DRIVER_FN" -s --no-drm || (sudo cat /var/log/nvidia-installer.log && false)
  #           nvidia-smi
  test-win-default:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print User name
        run: |
          [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
      - name: Install Visual Studio
        run: |
          .\.github\scripts\install_vs.ps1
  test-win-cpu:
    runs-on: "windows.2xlarge"
    steps:
      - uses: actions/checkout@v2
      - name: Print runner information
        run: (Get-WmiObject Win32_OperatingSystem).CSName
      - name: Print User name
        run: |
          [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
      - name: Install Visual Studio
        run: |
          .\.github\scripts\install_vs.ps1
  test-win-gpu:
    runs-on: "windows.8xlarge.nvidia.gpu"
    steps:
      - uses: actions/checkout@v2
      - name: Print runner information
        run: (Get-WmiObject Win32_OperatingSystem).CSName
      - name: Print User name
        run: |
          [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
      - name: Install Visual Studio
        run: |
          .\.github\scripts\install_vs.ps1
      - name: Print nvidia-smi
        shell: bash
        run: |
          .github/scripts/windows_cuda_install.sh
      - name: Print runner information
        run: nvidia-smi
