name: verify
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  SCCACHE_BUCKET: "ossci-compiler-cache"
  PYTHON_VERSION: "3.8"
  IN_CI: 1
  INSTALL_WINDOWS_SDK: 1
  VC_PRODUCT: "BuildTools"
  VC_VERSION: ""
  VS_VERSION: "16.8.6"
  VC_YEAR: "2019"

jobs:
  test-cuda-scripts:
    env:
      BUILD_ENVIRONMENT: pytorch-win-vs2019-cuda11-cudnn8-py3
      BUILD_WHEEL: 1
      CUDA_VERSION: "11.1"
      TORCH_CUDA_ARCH_LIST: "7.0"
      USE_CUDA: 1
      JOB_BASE_NAME: pytorch-win-vs2019-cuda11-cudnn8-py3-build
    runs-on: "windows.8xlarge.nvidia.gpu"
    steps:
      - uses: actions/checkout@v2
      - name: Clone pytorch
        uses: actions/checkout@v2
        with:
          repository: 'pytorch/pytorch'
          ref: 'gh/seemethere/151/head'
          submodules: 'recursive'
          path: 'pytorch'
      - name: Install Visual Studio 2019 toolchain
        shell: powershell
        run: |
          .\pytorch\.circleci\scripts\vs_install.ps1
      - name: Install Cuda
        shell: bash
        run: |
          ./pytorch/.circleci/scripts/windows_cuda_install.sh
      - name: Install Cudnn
        shell: bash
        run: |
          ./pytorch/.circleci/scripts/windows_cudnn_install.sh
