name: verify
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test-linux-cpu:
    runs-on: "linux.2xlarge"
    steps:
      - name: Print runner information
        run: cat /etc/os-release
  test-linux-gpu:
    runs-on: "linux.8xlarge.nvidia.gpu"
    steps:
      - name: Print runner information
        run: cat /etc/os-release
      - name: Install nvidia-smi
        run: |
            sudo yum groupinstall -y "Development Tools"
            DRIVER_FN="NVIDIA-Linux-x86_64-460.39.run"
            wget "https://s3.amazonaws.com/ossci-linux/nvidia_driver/$DRIVER_FN"
            sudo /bin/bash "$DRIVER_FN" -s --no-drm || (sudo cat /var/log/nvidia-installer.log && false)
            nvidia-smi
  # test-win-cpu:
  #   runs-on: "win.2xlarge"
  #   steps:
  #     - name: Print runner information
  #       run: (Get-WmiObject Win32_OperatingSystem).CSName
  # test-win-gpu:
  #   runs-on: "win.8xlarge.nvidia.gpu"
  #   steps:
  #     - name: Print runner information
  #       run: (Get-WmiObject Win32_OperatingSystem).CSName
  #     - name: Print nvidia-smi
  #       shell: bash
  #       run: |
  #         cuda_installer_link="https://ossci-windows.s3.amazonaws.com/${cuda_installer_name}.exe"

  #         curl --retry 3 -kLO $cuda_installer_link
  #         7z x ${cuda_installer_name}.exe -o${cuda_installer_name}
  #         cd ${cuda_installer_name}
  #         mkdir cuda_install_logs

  #         set +e

  #         ./setup.exe -s ${cuda_install_packages} -loglevel:6 -log:"$(pwd -W)/cuda_install_logs"
  #         nvidia-smi
